export enum NODE_ENV {
  DEV = 'development',
  PROD = 'production',
  STAGGING = 'stagging',
}

export enum ENV {
  MONGODB_URI = 'MONGODB_URI',
  NODE_ENV = 'NODE_ENV',
  SWAGGER_USER = 'TrustPadi',
  SWAGGER_PASSWORD = 'MasterOFtruth@1234#',
  NODE_DEV = 'development',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  SALT_ROUNDS = 'SALT_ROUNDS',
  ENCRYPTION_KEY = 'ENCRYPTION_KEY',
  AWS_S3_CONFIG_REGION = 'AWS_S3_CONFIG_REGION',
  AWS_S3_CONFIG_ACCESS_KEY = 'AWS_S3_CONFIG_ACCESS_KEY',
  AWS_S3_CONFIG_SECRET_ACCESS_KEY = 'AWS_S3_CONFIG_SECRET_ACCESS_KEY',
  AWS_S3_CONFIG_BUCKET_NAME = 'AWS_S3_CONFIG_BUCKET_NAME',
  AWS_S3_CONFIG_CLOUDFRONT_URL = 'AWS_S3_CONFIG_CLOUDFRONT_URL',
}

export enum ROLE {
  USER = 'USER'
}

export enum TOKEN_TYPES {
  RESET_PASSWORD = "reset_password",
  REFRESH = "refresh"
}